## This package provides two functions:
## 1. makeCacheMatrix: creates a special matrix object, that can cache its inverse
## 2. cacheSolve: solves the inverse of a matrix, generated by the makeCacheMatrix function. It
## returns an existing inverse if one exists, and solves and then caches it otherwise, for future usage

## Creates a matrix object, that can cache its inverse
## Provices the methods:
## set: set matrix object
## get: returns matrix object
## setInverse: sets inverse of matrix
## getInverse: returns the (possibly cached) inverse of matrix

makeCacheMatrix <- function(x = matrix()) {
    inv <- NULL
    set <- function(y) {
        x <<- y
        inv <<- NULL
    }
    get <- function() x
    setInverse <- function(inverse) inv <<- inverse
    getInverse <- function() inv
    list(set = set, get = get,
         setInverse = setInverse,
         getInverse = getInverse)
}


## Calculates the inverse of matrix generated by makeCacheMatrix

cacheSolve <- function(x, ...) {
    ## Return a matrix that is the inverse of 'x'
    inv <- x$getInverse()
    if(!is.null(inv)) {
        message("getting cached data")
        return(inv)
    }
    data <- x$get()
    inv <- solve(data, ...)
    x$setInverse(inv)
    inv
}
